name: Cloud Resume Challenge

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest boto3 moto

      - name: Run Python Tests
        run: |
          export AWS_DEFAULT_REGION='us-east-1'
          python -m pytest test_lambda/test_lambda.py

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cypress Dependencies
        run: npm install

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        id: apply
        run: |
          terraform apply -auto-approve
          echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_ENV
          echo "cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_ENV
          echo "api_url=$(terraform output -raw api_url)" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "bucket_name=${{ env.bucket_name }}"
          echo "cloudfront_distribution_id=${{ env.cloudfront_distribution_id }}"
          echo "api_url=${{ env.api_url }}"

      - name: Sync S3 Bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete --exclude '.git/*' --size-only
        env:
          AWS_S3_BUCKET: ${{ env.bucket_name }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'frontEnd'

  invalidate-cloudfront-distribution:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.cloudfront_distribution_id }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"

  update-script:
    needs: invalidate-cloudfront-distribution
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve API Gateway URL
        run: echo "API_URL=$(terraform output -raw api_url | tr -d '\r')" >> $GITHUB_ENV

      - name: Update script.js with API URL
        run: |
          sed -i "s|PLACEHOLDER_URL|${{ env.API_URL }}|" frontEnd/script.js

      - name: Sync Updated Script
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete --exclude '.git/*' --size-only
        env:
          AWS_S3_BUCKET: ${{ env.bucket_name }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'frontEnd'

  cypress-tests:
    needs: update-script
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cypress Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run --headless
        env:
          API_URL: ${{ env.API_URL }}

  cleanup:
    needs: deploy
    if: failure()  # Run only if the deploy job fails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve -var="state_bucket_name=${{ secrets.STATE_BUCKET_NAME }}"
